yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: node-modules

packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": npm:ansi-styles@*
      "#supports-color": npm:supports-color@*
