name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Access to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_PEM}}
          REMOTE_HOST: ${{secrets.EC2_IP}}
          REMOTE_USER: ubuntu

      - name: Test
        run: |
          mkdir test-directory
