name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Access to EC2
        run: |
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_IP}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_PEM}}
          script: |
            mkdir test-directory
