name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Access to EC2
        run: |
          echo ${{secrets.EC2_PEM}} > access.pem
          ssh -i access.pem ubuntu@${{secrets.EC2_IP}}

      - name: Test
        run: |
          mkdir test-directory
