name: get-now-fee

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r nowFee-requirements.txt
      - name: Run nowFee.py
        run: |
          python scripts/updatechart.py
      - name: Commits
        run: |
          git config --local user.email "khr5k0228@gmail.com"
          git config --local user.name "hyeongrok7874"
          git add src/public/data/chart.json 
          git commit -m "Auto update chart.json"
      - name: Push
        run: |
          git push
