name: moip-ci

on:
  push:
    branches:
      - main

jobs:
  moip-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setting to build
        uses: actions/setup-node@master
        with:
          node-version: '20'  

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Linting
        run: pnpm lint

      - name: Building
        run: pnpm build