name: moip-cd

on:
  workflow_run:
    workflows: ["moip-ci"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'success'}}

    steps:
      - uses: actions/checkout@v3

      - name: Access to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_IP}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_PEM}}
          script: |
            pnpm -v
            sh /home/ubuntu/moip-cd.sh

      - run: echo "CD Success"

  on-failure:
    runs-on: ubuntu-latest

    if: ${{github.event.workflow_run.conclusion == 'failure'}}

    steps:
      - run: echo "CI workflow was a failure"